version: "3.5"

services:
  nest_start_postgres:
    container_name: nest_start_postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portal
      PGDATA: /data/postgres
    volumes:
      - postgres:/var/www/nest_start/docker-volumes/postgres
    ports:
      - "5432:5432"
    networks:
      - nest_start_net
    restart: unless-stopped
  nest_start_pgadmin:
    container_name: nest_start_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: nest_start@admin.com
      PGADMIN_DEFAULT_PASSWORD: nest_start
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/ww/nest_start/docker-volumes/pgadmin
    ports:
      - "5050:80"
    networks:
      - nest_start_net
    restart: unless-stopped
networks:
  nest_start_net:
    driver: bridge
volumes:
  postgres:
  pgadmin:


